global using BKAssembly;
global using BKAssembly.Extensions;
global using BKAssembly.WinForms;
global using BKAssembly.WinForms.Extensions;
global using BKAssembly.WPF;
global using BKAssembly.WPF.Extensions;
global using CommunityToolkit.Mvvm.ComponentModel;
global using CommunityToolkit.Mvvm.Input;
global using Microsoft.Extensions.Configuration;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.Extensions.Hosting;
global using Wpf.Ui;
global using Wpf.Ui.Extensions;
global using Wpf.Ui.Abstractions;
global using Wpf.Ui.Abstractions.Controls;
global using WpfUi = Wpf.Ui.Controls;
